version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/composetest
      # for development only
      # bind the source fs in host to container fs
    environment:
      FLASK_ENV: development
      # for development only
      # Flask will reload the changes automatically
      # No need to rebuild the image on code changes.
  redis:
    image: "redis:alpine"
